### PR TITLE
Walking & Resting Heart Rate, HeartRateVariability, ExerciseTime

### PR DESCRIPTION
**Pull request by matthiasn**
This PR adds some additional sample types:
- Walking Heart Rate
- Resting Heart Rate
- HeartRateVariability
- ExerciseTime

Published on **[npm](https://www.npmjs.com/package/@matthiasn/rn-apple-healthkit)** as `@matthiasn/rn-apple-healthkit`

### CODE REVIEW

**Comment by EJohnF** [comment]
Thanks for you contribution! :)
Couple moments:
merge conflicts and need to update docs for new functionality

**Comment by alishaevn** [comment]
@matthiasn Do you intend to correct the conflicting files so that this PR can be merged in?

**Comment by matthiasn** [comment]
@alishaevn just looked at it, happy to do that including adding to the docs if there's a chance of actually getting the PR merged. @terrillo is this repository still maintained? The number of open PRs has me suspect otherwise.

**Comment by kamwoz** [comment]
Any news? Still open :|

**Comment by IceDev-xyz** [comment]
When using your library I can't build the project, the following error appears

`'React/RCTBridgeModule.h' file not found`

Any ideas?

**Comment by kamwoz** [comment]
@matthiasn hey I installed your package and I'm still getting an error: 
```
        AppleHealthKit.getRestingHeartRate({
          startDate: (new Date(2019,10,11)).toISOString(),
          unit: 'bpm',
        }, (err, results) => {
           // error
        });
```
"error getting heart rate samples" - that is error message. You have any idea why is it happening? I have data in my Health app

**Comment by skryl** [comment]
@terrillo any update on this?

**Comment by israr-shaikh** [comment]
To get Resting Heart Rate, use this link https://github.com/israr-shaikh/rn-apple-healthkit 
it's the latest fork and codes are updated.

**Comment by klabusta** [comment]
I've had similar problems. For getWalkingHeartRateAverage I had to add my own permission: 'WalkingHeartRateAverage' which is not part of the permission constants.

**Pull request closed without merging**
